/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Random;
import logic.WMFile;
import logic.WMData;

/**
 *
 * @author Wojtek
 */
public class WMKolowy extends javax.swing.JPanel {

    private Color[] kolory;
    private Random losowa;

    /**
     * Creates new form WMKolowy
     */
    public WMKolowy() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        try {
            super.paint(g);
            losowa = new Random();
            kolory = new Color[WMFile.odczyt(WMData.getSciezka()).length];
            for (int i = 0; i < kolory.length; i++) {
                kolory[i] = new Color(losowa.nextInt(255), losowa.nextInt(255), losowa.nextInt(255));
            }

            int width = getWidth() - WMData.getMargines() * 2;
            int height = getHeight() - WMData.getMargines() * 3;
            int suma = 0;
            for (int i : WMFile.odczyt(WMData.getSciezka())) {
                suma += i;
            }
            double x = 360.0 / suma;
            int poczatek = 0;
            for (int i = 0; i < WMFile.odczyt(WMData.getSciezka()).length; i++) {
                g.setColor(kolory[i]);
                g.fillArc(WMData.getMargines(), WMData.getMargines() * 2, width, height, poczatek, (int) ((WMFile.odczyt(WMData.getSciezka()))[i] * poczatek));
                poczatek += (int) (WMFile.odczyt(WMData.getSciezka())[i] * x);
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
