/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.io.FileNotFoundException;
import java.io.IOException;
import logic.WMData;
import logic.WMFile;

/**
 *
 * @author Wojtek
 */
public class WMSlupkowy extends javax.swing.JPanel {

    /**
     * Creates new form WMSlupkowy
     */
    public WMSlupkowy() {
        initComponents();
    }

    public void paint(Graphics g) {
        super.paint(g);
        try {
            int freeSpace = this.getHeight() - 2 * WMData.getMargines();
            double resize = (double) freeSpace / WMData.getMaxData(WMFile.odczyt(WMData.getSciezka())) - 0.002;
            int szerokosc = (this.getWidth() - WMData.getMargines() - 10) / WMFile.odczyt(WMData.getSciezka()).length;
            for (int i = 0; i < WMFile.odczyt(WMData.getSciezka()).length; i++) {

                g.setColor(WMData.getKolor());
                g.drawLine(this.getHeight() + WMData.getMargines(), WMData.getMargines(), this.getWidth(), WMData.getMargines());
                g.fillRect(i * szerokosc + WMData.getMargines(), (int) (getHeight() - WMFile.odczyt(WMData.getSciezka())[i] * resize - WMData.getMargines()), szerokosc - 1, (int) (WMFile.odczyt(WMData.getSciezka())[i] * resize));
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
